services:
  - type: web
    name: stellar-analytics-backend
    runtime: python
    rootDir: stellar_backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.11.8"